# Generated by Django 4.2.20 on 2025-03-30 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='status',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('cartao', 'Cartão de Crédito/Débito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], default='cartao', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='troco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
